### ISSUE TITLE
Question: How to handle sub charts in a HelmRelease?

### ISSUE THREAD

**Issue by Karnich** [fluxcd/helm-operator-get-started#18]
trying to add Istio with a helmRelease. The helmRelease gets created but it fails along the way. The operator doesnt give any error but when getting the output of the helmRelease i find this:

"message": "could not update dependencies in /tmp/flux-working725546946/charts/istio: Error: no repository definition for , , , , , , , , , , , , , , . Please add them via 'helm repo add'\nNote that repositories must be URLs or aliases. For example, to refer to the stable\nrepository, use \"https://kubernetes-charts.storage.googleapis.com/\" or \"@stable\" instead of\n\"stable\". Don't forget to add the repo, too ('helm repo add').\n",

**Comment by stefanprodan** [comment]
The Istio chart has the subcharts included in the [charts](https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/charts) dir. Flux expects for the dependencies to be fetched at runtime. 

You can disable the dependencies build with `skipDepUpdate`:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  skipDepUpdate: true
  chart:
    git: git@github.com:stefanprodan/gitops-helm
    path: charts/istio
    ref: master
  values: {}
```
