### ISSUE TITLE
does this work fine with public helm charts?

### ISSUE THREAD

**Issue by chicco785** [fluxcd/helm-operator-get-started#24]
The approach looks very interesting, before testing it, I wonder if (as I supposed from reading the configuration flow) this works fine also for public helm charts. Also for owned charts we would like to keep the git repo separate and only interact with the helm charts repo. Thanks for the advice!

**Comment by stefanprodan** [comment]
Yes, see sealed secrets example:

```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: adm
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.0.1
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.7.0
```
